In [ ]:
#DataFrame的创建方式
import numpy as np
import pandas as pd
#1:通过Series来创建
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([6,7,8,9,10])
df=pd.DataFrame({'第一列':s1,'第二列':s2})
# df
type(df['第一列'])
#通过字典创建
df=pd.DataFrame({
    # 'id':[1,2,3,4,5],
    'name':['tom','jack','alice','bob','allen'],
    'age':[15,17,20,26,30],
    'score':[60.5,80,30.6,70,83.5]
     },index=[1,2,3,4,5],columns=['name','age','score']
     )
df

    name  age  score
1    tom   15   60.5
2   jack   17   80.0
3  alice   20   30.6
4    bob   26   70.0
5  allen   30   83.5

In [21]:
#DataFrame的属性
print('行索引:\n',df.index)
print('列标签:\n',df.columns)
print('DataFrame的值:\n',df.values)
print('DataFrame的维度:\n',df.ndim)
print('DataFrame的数据类型:\n',df.dtypes)
print('DataFrame的形状:\n',df.shape)
print('DataFrame的元素个数:\n',df.size)

行索引:
 Index([1, 2, 3, 4, 5], dtype='int64')
列标签:
 Index(['name', 'age', 'score'], dtype='object')
DataFrame的值:
 [['tom' 15 60.5]
 ['jack' 17 80.0]
 ['alice' 20 30.6]
 ['bob' 26 70.0]
 ['allen' 30 83.5]]
DataFrame的维度:
 2
DataFrame的数据类型:
 name      object
age        int64
score    float64
dtype: object
DataFrame的形状:
 (5, 3)
DataFrame的元素个数:
 15

In [30]:
# 行列转置
# df
df.T
df.T.index
df.T.columns
df

    name  age  score
1    tom   15   60.5
2   jack   17   80.0
3  alice   20   30.6
4    bob   26   70.0
5  allen   30   83.5

In [ ]:
# loc iloc at iat
# 获取某行的数据
print(' 切片获取第一行:\n',df[0:1])
print(' loc显式索引获取第4行:\n',df.loc[4])
print(' iloc隐式索引获取第4行:\n',df.iloc[3])
print(' 切片获取第四行:\n',df[3:4])
print(' 获取第二行:\n',df[1:2])

 切片获取第一行:
   name  age  score
1  tom   15   60.5
 loc显式索引获取第4行:
 name      bob
age        26
score    70.0
Name: 4, dtype: object
 iloc隐式索引获取第4行:
 name      bob
age        26
score    70.0
Name: 4, dtype: object
 切片获取第四行:
   name  age  score
4  bob   26   70.0
 获取第二行:
    name  age  score
2  jack   17   80.0

In [ ]:
# 获取某列数据
print('显式获取某列数据:\n',df.loc[:,'name'])
print('隐式获取某列数据:\n',df.iloc[:,0])

显式获取某列数据:
 1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
显隐获取某列数据:
 1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object

In [83]:
print(df)
# 获取单个元素
print('显式索引行标签+列名字获取单个元素:',df.at[3,'score']) #显式索引行标签+列名字获取单个元素
print('隐式索引行标签+列标签获取单个元素:',df.iat[2,2]) #隐式索引行标签+列标签获取单个元素
print('显式索引行标签+列名字获取单个元素:',df.loc[3,'score'])
print('隐式索引行标签+列标签获取单个元素:',df.iloc[2,2])

    name  age  score
1    tom   15   60.5
2   jack   17   80.0
3  alice   20   30.6
4    bob   26   70.0
5  allen   30   83.5
显式索引行标签+列名字获取单个元素: 30.6
隐式索引行标签+列标签获取单个元素: 30.6
显式索引行标签+列名字获取单个元素: 30.6
隐式索引行标签+列标签获取单个元素: 30.6

In [ ]:
# 访问DataFrame的数据的方式
# 获取单列数据
print(df['name'])  #输出结果类型是一个Series
print(df.name)   #输出结果类型是一个Series
print(df[['name']])  #输出结果类型是一个DataFrame
#获取多列数据
print(df[['name','age']])  #输出结果类型是一个DataFrame

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
    name
1    tom
2   jack
3  alice
4    bob
5  allen
    name  age
1    tom   15
2   jack   17
3  alice   20
4    bob   26
5  allen   30

In [92]:
#查看部分数据
print('获取前2行的数据:\n',df.head(2))
print('获取最后3行的数据:\n',df.tail(3))

获取前2行的数据:
    name  age  score
1   tom   15   60.5
2  jack   17   80.0
获取最后3行的数据:
     name  age  score
3  alice   20   30.6
4    bob   26   70.0
5  allen   30   83.5

In [ ]:
#使用布尔索引筛选数据
df[(df.score>70) & (df.age<20)]

   name  age  score
2  jack   17   80.0

In [ ]:
#随机抽样.
df.sample(3)  #随机取3条,里面的参数自己可以设置

   name  age  score
2  jack   17   80.0

In [118]:
df

    name  age  score
1    tom   15   60.5
2   jack   17   80.0
3  alice   20   30.6
4    bob   26   70.0
5  allen   30   83.5

In [126]:
#DataFrame中常用函数
df.head() #查看前n行数据,默认是5行
df.tail(3) #查看后n行数据,默认是5行
print(df.isin(['jack',20])) #查看元素是否包含在参数集合中
print(df.isna())  #查看元素是否是缺失值

    name    age  score
1  False  False  False
2   True  False  False
3  False   True  False
4  False  False  False
5  False  False  False
    name    age  score
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [153]:
# print(df['score'].sum()) #求某一列的总和
# print(df['score'].max()) #求某一列的最大值
# print(df['age'].min()) 
# print(df['age'].mean()) 
# print('每一列非缺失值的个数:\n',df.count()) #每一列非缺失值的个数
# print('每行数据出现的次数:\n',df.value_counts()) #每行数据出现的此时
# print(df.drop_duplicates()) #去重
# print(df.duplicated(subset=['age']))  #检查是否有重复的
print('随机抽样:\n',df.sample()) #随机抽样
print('替换值:\n',df.replace(15,30)) #替换值
print('累计和:',df.cumsum()) #累计和
print(df.cummax())

随机抽样:
   name  age  score
1  tom   15   60.5
替换值:
     name  age  score
1    tom   30   60.5
2   jack   17   80.0
3  alice   20   30.6
4    bob   26   70.0
5  allen   30   83.5
累计和:                    name  age  score
1                   tom   15   60.5
2               tomjack   32  140.5
3          tomjackalice   52  171.1
4       tomjackalicebob   78  241.1
5  tomjackaliceboballen  108  324.6
  name  age  score
1  tom   15   60.5
2  tom   17   80.0
3  tom   20   80.0
4  tom   26   80.0
5  tom   30   83.5

In [160]:
#排序
print(df.sort_index(ascending=False))

    name  age  score
5  allen   30   83.5
4    bob   26   70.0
3  alice   20   30.6
2   jack   17   80.0
1    tom   15   60.5

In [165]:
print(df.score.sort_values(ascending=False))
print(df.sort_values(by=['score','age']))

5    83.5
2    80.0
4    70.0
1    60.5
3    30.6
Name: score, dtype: float64
    name  age  score
3  alice   20   30.6
1    tom   15   60.5
4    bob   26   70.0
2   jack   17   80.0
5  allen   30   83.5

In [4]:
df.nlargest(2,columns=['score','age'])
df.nsmallest(2,columns=['score','age'])

    name  age  score
3  alice   20   30.6
1    tom   15   60.5

In [ ]:
# 练习1：学生成绩分析
# 某班级的学生成绩如下，请进行数据分析
# 1：计算每位学生的总分和平均分
# 2：找出数学成绩高于90分或者英语成绩高于85分的学生
# 3：按总分又高到底排名，输出前3名的学生
scores=pd.DataFrame({
    '姓名':['张三','李四','王五','赵六','钱七'],
    '数学':[85,92,78,88,95],
    '英语':[90,88,85,92,80],
    '物理':[75,80,88,85,90]
})
# con1=(scores['数学']>90) | (scores['英语']>90 )| (scores['物理']>90)
# con2=scores['英语']>85
# con3=scores[con1| con2]
# 检查每行是否有科目 > 90
# has_high_score=(scores[['数学','英语','物理']]>90).any(axis=1)
# # 英语成绩 > 85
# english_high=scores['英语']>85
# result = df[has_high_score | english_high]
print(scores)
# print('学生的总分:',scores.iloc[:,1:].sum(axis=1))
# print('学生的平均分:',scores.iloc[:,1:].mean(axis=1))
# print('绩高于90分或者英语成绩高于85分的学生:')
# print(result)
# print(scores.head(3))
scores['总分']=scores[['数学','英语','物理']].sum(axis=1)
scores['平均分']=scores[['数学','英语','物理']].mean(axis=1)
scores[(scores['数学']>90)|(scores['英语']>85)]
# scores.sort_values('总分',ascending=False).head(3)
scores.nlargest(3,columns='总分')
scores.nlargest(3,columns=['总分'])

   姓名  数学  英语  物理
0  张三  85  90  75
1  李四  92  88  80
2  王五  78  85  88
3  赵六  88  92  85
4  钱七  95  80  90

   姓名  数学  英语  物理   总分        平均分
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667

In [82]:
# 练习2:销售数据分析
# 某公司销售数据如下
# 1：计算每种产品的总销售额=单价*数量
# 2：找出销售额最高的产品
# 3：按照销售额由高到低排列，并输出所有产品信息
data={
      '产品名称':['A','B','C','D'],
      '单价':[100,150,200,120],
      '销量':[50,30,20,40]
      }
sales=pd.DataFrame(data)
# 计算每种产品的总销售额=单价*数量
print('计算每种产品的总销售额=单价*数量:')
sales['总销售额']=sales['单价']*sales['销量']
# 找出销售额最高的产品
sales.nlargest(1,columns='总销售额')
#按照销售额由高到低排列，并输出所有产品信息
sales.sort_values('总销售额',ascending=False)

计算每种产品的总销售额=单价*数量:

  产品名称   单价  销量  总销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000

In [93]:
# 1.计算每位用户的总消费金额(消费金额=商品单价x购买数量)
# 2.找出消费金额最高的用户，并输出其所有信息
# 3.计算所有用户的平均消费金额(保留2位小数)
# 4.统计电子产品的总购买数量
data1={
    '用户ID':[101,102,103,104,105],
    '用户名':['Alice','Bob','Charlie','David','Eve'],
    '商品类别':['电子产品','服饰','电子产品','家居','服饰'],
    '商品单价':[1200,300,800,150,200],
    '购买数量':[1,3,2,5,4]
}
df=pd.DataFrame(data1)
# 计算每位用户的总消费金额(消费金额=商品单价x购买数量)
df['总消费金额']=df['商品单价']*df['购买数量']
# 找出消费金额最高的用户，并输出其所有信息
df.nlargest(1,columns='总消费金额')
# 计算所有用户的平均消费金额(保留2位小数)
df['总消费金额'].mean()
# 统计电子产品的总购买数量
df[df['商品类别']=='电子产品']['购买数量'].sum()

# df

3