In [ ]:
#数据导入
import numpy as np
import pandas as pd
df=pd.read_csv('data/employee.csv')
# print(df.dtypes)
# type(df)
df
# df.salary.mean()

,employee_id,name,gender,age,department,salary,work_years,is_left,score
0,1,员工1,男,23,技术部,6500,1,0,65
1,2,员工2,女,24,技术部,7000,1,0,68
2,3,员工3,男,25,技术部,8000,2,0,72
3,4,员工4,女,26,技术部,8500,2,0,75
4,5,员工5,男,27,技术部,9500,3,0,78
...,...,...,...,...,...,...,...,...,...
295,296,员工296,女,37,财务部,17800,7,0,93
296,297,员工297,男,36,管理层,26000,10,0,94
297,298,员工298,女,37,管理层,27000,10,0,95
298,299,员工299,男,38,管理层,28000,11,0,96
299,300,员工300,女,39,管理层,29000,11,0,97

In [8]:
#数据导出
df.to_csv('data/new_employee.csv')

In [15]:
# 数据导入
# 读取json格式的数据
# import json
df1=pd.read_json('data/employee.json')
df1.to_json('data/new_employee.json')
df1
# print(type(df1))

,employee_id,name,gender,age,department,salary,work_years,is_left,score
0,1,员工1,男,23,技术部,6500,1,0,65
1,2,员工2,女,24,技术部,7000,1,0,68
2,3,员工3,男,25,技术部,8000,2,0,72
3,4,员工4,女,26,技术部,8500,2,0,75
4,5,员工5,男,27,技术部,9500,3,0,78
...,...,...,...,...,...,...,...,...,...
295,296,员工296,女,37,财务部,17800,7,0,93
296,297,员工297,男,36,管理层,26000,10,0,94
297,298,员工298,女,37,管理层,27000,10,0,95
298,299,员工299,男,38,管理层,28000,11,0,96
299,300,员工300,女,39,管理层,29000,11,0,97

In [25]:
#复杂格式的json文件读取
import json
with open('data/employee_complex.json','r',encoding='utf-8') as f:
 data =json.load(f)
#  print(type(data))
df3=pd.DataFrame(data['employees'])
print(data['employees'])
df3

[{'id': 1, 'name': '张三', 'gender': '男', 'age': 28, 'department': {'dept_name': '技术部', 'location': '北京', 'manager': '李总监'}, 'salary': {'base': 12000, 'bonus': 3000, 'tax': 1500}, 'work_years': 3, 'is_left': False, 'performance': [{'year': 2023, 'score': 85}, {'year': 2024, 'score': 88}], 'skills': ['Python', 'MySQL', 'Linux']}, {'id': 2, 'name': '李四', 'gender': '女', 'age': 32, 'department': {'dept_name': '人事部', 'location': '上海', 'manager': '王经理'}, 'salary': {'base': 9000, 'bonus': 2000, 'tax': 1000}, 'work_years': 5, 'is_left': False, 'performance': [{'year': 2023, 'score': 80}, {'year': 2024, 'score': 86}], 'skills': ['招聘', '培训', '劳动法']}, {'id': 3, 'name': '王五', 'gender': '男', 'age': 25, 'department': {'dept_name': '技术部', 'location': '深圳', 'manager': '李总监'}, 'salary': {'base': 8000, 'bonus': 1500, 'tax': 800}, 'work_years': 2, 'is_left': True, 'performance': [{'year': 2023, 'score': 70}, {'year': 2024, 'score': None}], 'skills': ['Java', 'Git']}, {'id': 4, 'name': '赵六', 'gender': '女', 'age': 30, 'department': {'dept_name': '市场部', 'location': '广州', 'manager': '张总监'}, 'salary': {'base': 15000, 'bonus': 5000, 'tax': 2200}, 'work_years': 4, 'is_left': False, 'performance': [{'year': 2023, 'score': 92}, {'year': 2024, 'score': 95}], 'skills': ['营销', '策划', 'PPT']}, {'id': 5, 'name': '孙七', 'gender': '男', 'age': 35, 'department': {'dept_name': '技术部', 'location': '杭州', 'manager': '李总监'}, 'salary': {'base': 18000, 'bonus': 6000, 'tax': 2800}, 'work_years': 8, 'is_left': False, 'performance': [{'year': 2022, 'score': 89}, {'year': 2023, 'score': 94}, {'year': 2024, 'score': 96}], 'skills': ['Python', '大数据', '机器学习']}]

,id,name,gender,age,department,salary,work_years,is_left,performance,skills
0,1,张三,男,28,"{'dept_name': '技术部', 'location': '北京', 'manage...","{'base': 12000, 'bonus': 3000, 'tax': 1500}",3,False,"[{'year': 2023, 'score': 85}, {'year': 2024, '...","[Python, MySQL, Linux]"
1,2,李四,女,32,"{'dept_name': '人事部', 'location': '上海', 'manage...","{'base': 9000, 'bonus': 2000, 'tax': 1000}",5,False,"[{'year': 2023, 'score': 80}, {'year': 2024, '...","[招聘, 培训, 劳动法]"
2,3,王五,男,25,"{'dept_name': '技术部', 'location': '深圳', 'manage...","{'base': 8000, 'bonus': 1500, 'tax': 800}",2,True,"[{'year': 2023, 'score': 70}, {'year': 2024, '...","[Java, Git]"
3,4,赵六,女,30,"{'dept_name': '市场部', 'location': '广州', 'manage...","{'base': 15000, 'bonus': 5000, 'tax': 2200}",4,False,"[{'year': 2023, 'score': 92}, {'year': 2024, '...","[营销, 策划, PPT]"
4,5,孙七,男,35,"{'dept_name': '技术部', 'location': '杭州', 'manage...","{'base': 18000, 'bonus': 6000, 'tax': 2800}",8,False,"[{'year': 2022, 'score': 89}, {'year': 2023, '...","[Python, 大数据, 机器学习]"

In [4]:
#缺失值的处理
import pandas as pd
import numpy as np
import json
s=pd.Series([12,25,np.nan,None,pd.NA])
df=pd.DataFrame([[1,pd.NA,2],[2,3,5],[None,4,6]],columns=['第一列','第二列','第三列'])
print(s)
# 检查是否是缺失值
print(s.isna())
print(s.isnull())
print(df)
print(df.isna())
print(df.isnull())
# print(df.isna().count())
print(df.isna().sum())
print(df.isna().sum(axis=1))

0      12
1      25
2     NaN
3    None
4    <NA>
dtype: object
0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
第一列    1
第二列    1
第三列    0
dtype: int64
0    1
1    0
2    1
dtype: int64

In [65]:
#删除缺失值
print(s)
s.dropna()  #Series删除的是某个元素的纪录
print(df)
df.dropna() #dataframe删除缺失值是删除整条的纪录
df.dropna(how='all') #dataframe删除缺失值是删除整条的纪录，可以加参数how=all，如果所有的值是缺失值才删除整行
print(df.dropna(thresh=1)) #至少有n个值不是缺失值,则保留
print(df.dropna(axis=1)) #删除一整列有缺失值的列
print(df.dropna(subset=['第一列','第二列'])) #指定某列有缺失值,则删除这一行的数据

0      12
1      25
2     NaN
3    None
4    <NA>
dtype: object
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第三列
0    2
1    5
2    6
   第一列 第二列  第三列
1  2.0   3    5

In [3]:
#填充缺失值
pd.read_csv('data/xian_weather.csv')

print(df.isna().sum(axis=0))
# print(df.fillna({'high_temp':20,'low_temp':10})) #使用字典来填充
# print(df.fillna(df['high_temp'].mean()))
print(df)
# print(df.fillna({'high_temp':df['high_temp'].mean()})) #用平均值填充缺失值
# print(df.fillna(df[['high_temp','low_temp']].mean()))#用平均值填充缺失值的另一种写法
print(df.ffill()) #用前面的值填充
print(df.bfill()) #用后面的值填充

NameError: name 'pd' is not defined

In [90]:
#重复数据处理
data={
    'name':['alice','alice','bob','alice','jack','bob'],
    'age':[26,25,30,25,35,30],
    'city':['NY','NY','LA','NY','SF','LA']
}
df=pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [95]:
print(df.duplicated()) #一整条记录都一样,标记为重复,返回为True
print(df.drop_duplicates(subset=['name'])) #根据指定的列去重
print(df.drop_duplicates(subset=['name'],keep='last')) #保留最后一次的数据

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool
    name  age city
0  alice   26   NY
2    bob   30   LA
4   jack   35   SF
    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [104]:
#数据类型转换表
df=pd.read_csv('data/employee.csv')
df.dtypes

employee_id     int64
name           object
gender         object
age             int64
department     object
salary          int64
work_years      int64
is_left         int64
score           int64
dtype: object

In [108]:
# 类型转换
df['age']=df['age'].astype('int16')
df['gender']=df['gender'].astype('category')
df.dtypes
df.gender

0      男
1      女
2      男
3      女
4      男
      ..
295    女
296    男
297    女
298    男
299    女
Name: gender, Length: 300, dtype: category
Categories (2, object): ['女', '男']

In [112]:
df['is_male']=df['gender'].map({'男':True,'女':False})
df.is_male

0       True
1      False
2       True
3      False
4       True
       ...
295    False
296     True
297    False
298     True
299    False
Name: is_male, Length: 300, dtype: category
Categories (2, bool): [False, True]

In [125]:
#数据变形
data={
    'ID':[1,2],
    'name':['alice','bob'],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89],
}
df=pd.DataFrame(data)
df.T#行列转置
df
'''
id name 科目 分数
1  alice math 90
1  alice english 88
1  alice Science 95
2  alice math 85
2  alice english 92
2  alice Science 89
'''

'\nid name 科目 分数\n1  alice math 90\n1  alice english 88\n1  alice Science 95\n2  alice math 85\n2  alice english 92\n2  alice Science 89\n'

In [127]:
# 宽表转换成长表
df2=pd.melt(df,id_vars=['ID','name'],var_name='科目',value_name='分数')
df2.sort_values('name')
print(df)
print(df2)

   ID   name  Math  English  Science
0   1  alice    90       88       95
1   2    bob    85       92       89
   ID   name       科目  分数
0   1  alice     Math  90
1   2    bob     Math  85
2   1  alice  English  88
3   2    bob  English  92
4   1  alice  Science  95
5   2    bob  Science  89

In [128]:
# 长表转款表
pd.pivot(df2,index=['ID','name'],columns='科目',values='分数')

科目        English  Math  Science
ID name
1  alice       88    90       95
2  bob         92    85       89

In [6]:
#数据分列
data={
    'ID':[1,2],
    'name':['alice smith','bob james'],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89],
}
df=pd.DataFrame(data)
# df.T#行列转置
df
df[['first_name','last_name']]=df['name'].str.split(' ',expand=True)
df
# df

   ID         name  Math  English  Science first_name last_name
0   1  alice smith    90       88       95      alice     smith
1   2    bob james    85       92       89        bob     james

In [9]:
#数据分箱
# pd.cut(x='',bins='',labels='')
df=pd.read_csv('data/employee.csv')
df.head(10)

,employee_id,name,gender,age,department,salary,work_years,is_left,score
0,1,员工1,男,23,技术部,6500,1,0,65
1,2,员工2,女,24,技术部,7000,1,0,68
2,3,员工3,男,25,技术部,8000,2,0,72
3,4,员工4,女,26,技术部,8500,2,0,75
4,5,员工5,男,27,技术部,9500,3,0,78
5,6,员工6,女,28,技术部,10000,3,0,80
6,7,员工7,男,29,技术部,11000,4,0,82
7,8,员工8,女,30,技术部,12000,4,0,85
8,9,员工9,男,31,技术部,13000,5,0,86
9,10,员工10,女,32,技术部,14000,5,0,88

In [44]:
df1=df.head(20)[['employee_id','salary']]
df1

    employee_id  salary
0             1    6500
1             2    7000
2             3    8000
3             4    8500
4             5    9500
5             6   10000
6             7   11000
7             8   12000
8             9   13000
9            10   14000
10           11    6800
11           12    7200
12           13    8200
13           14    8600
14           15    9600
15           16   10200
16           17   11200
17           18   12200
18           19   13200
19           20   14200

In [50]:
#数据分段,分箱，划分区间
# pd.cut(df1['salary'],bins=4).value_counts()#bins=整数,就分成n段
# pd.cut(df1['salary'],bins=[0,5000,10000,15000,20000,30000]).value_counts()#bins=列表,根据区间划分
df1['收入范围']=pd.cut(df1['salary'],bins=[0,5000,10000,15000,20000,30000],labels=['第一','第二','第三','第四','第五'])#bins=列表,根据区间划分
# pd.cut(df1['salary'],bins=3)#bins=列表,根据区间划分
df1
# 6492.5-10250.0-10250.0
pd.qcut(df1['salary'],3).value_counts()

salary
(6499.999, 8533.333]     7
(11133.333, 14200.0]     7
(8533.333, 11133.333]    6
Name: count, dtype: int64

In [76]:
df=pd.read_csv('data/employee.csv')
df1=df.head(20)
df['年龄组成']=pd.cut(df['age'],bins=[0,15,25,30,40],labels=['未成年','青年','中年','中老年'])
# pd.qcut(df['age'],q=3).value_counts()
df.value_counts().head(20)
df['年龄组成'].value_counts(())
df.head((10))
df['gender']=df['gender'].astype('category')
df['gender'].value_counts()
print(df['gender'].dtype)

category

In [101]:
# df.reindex(),df.rename(),df.reset_index()
df=pd.DataFrame({
    'name':['jack','alice','tom','bob'],
    'age':[20,30,40,50],
    'gender':['female','male','female','male']
     }
)
df.set_index('name',inplace=True)
df.reset_index(inplace=True)

df.rename(columns={'age':'person_age'},index={0:4},inplace=True)
df

    name  person_age  gender
4   jack          20  female
1  alice          30    male
2    tom          40  female
3    bob          50    male

In [105]:
#设置属性
df.index=[1,2,3,4]
df.columns=['姓名','年龄','性别']
df

      姓名  年龄      性别
1   jack  20  female
2  alice  30    male
3    tom  40  female
4    bob  50    male

In [ ]:
#时间数据的分析处理
d=pd.Timestamp('2026-03-31 13:23:25')
d1=pd.Timestamp('2026-03-31 13:23:26')
d
# print(type(d))
print((d.year))
print((d.month))
print((d.day))
print((d.date()))
print((d.time()))
print((d.hour))
print((d.minute))
print((d.second))
print(('是否是月底:',d.is_month_end))
print('星期几:',d.day_name())
print('转换为以天为周期:',d.to_period('D'))
print('转换为季度为周期:',d.to_period('Q'))
print('转换为年度为周期:',d.to_period('Y'))
print('转换为月度为周期:',d.to_period('M'))
print('转换为周为周期:',d.to_period('W'))

2026
3
31
2026-03-31
13:23:25
13
23
25
('是否是月底:', True)
星期几: Tuesday
转换为以天为周期: 2026-03-31
转换为季度为周期: 2026Q1
转换为年度为周期: 2026
转换为月度为周期: 2026-03
转换为周为周期: 2026-03-30/2026-04-05

In [ ]:
#数据类型转换,字符串转化为日期类型
a=pd.to_datetime('2026-03-31 13:23:25')
print(a)
print(type(a))
print(a.day_name())

2026-03-31 13:23:25
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
Tuesday

In [147]:
# DataFrame日期转换
df=pd.DataFrame({
    'sales':[100,200,300],
    'date':['20250601','20250602','20250603']
})
df['datetime']=pd.to_datetime(df['date'])
# df
# print(df.info())
# print(df['datetime'].dt.day_name())
df['week']=df['datetime'].dt.day_name()
df['datetime'].dt.year

0    2025
1    2025
2    2025
Name: datetime, dtype: int32

In [207]:
# csv文件转换
df=pd.read_csv('data/xian_weather.csv',parse_dates=['date'])
# df.info()
# df['timedate']=pd.to_datetime(df['date'])
# df['timedate'].dt.day_name()

df.info()

# df['date'].dt.year
df['date'].dt.day_name()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         30 non-null     datetime64[ns]
 1   high_temp    18 non-null     float64
 2   low_temp     18 non-null     float64
 3   weather      25 non-null     object
 4   wind         30 non-null     object
 5   air_quality  22 non-null     object
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 1.5+ KB

         date  high_temp  low_temp weather   wind air_quality
0  2025-03-21       18.0       7.0       晴  东北风2级           良
1  2025-03-22        NaN       NaN      多云   东风3级           良
2  2025-03-23        NaN      11.0      小雨   南风3级         NaN
3  2025-03-24       16.0       NaN       阴   西风2级           良
4  2025-03-25       19.0      10.0     NaN   北风2级           优
5  2025-03-26        NaN       NaN      多云  东南风3级           良
6  2025-03-27       24.0      14.0       晴  西南风2级         NaN
7  2025-03-28        NaN      13.0     NaN  东北风3级           良
8  2025-03-29       25.0      15.0       晴   东风2级           良
9  2025-03-30        NaN       NaN      小雨   南风2级        轻度污染
10 2025-03-31       21.0      11.0      多云   西风3级         NaN
11 2025-04-01       26.0       NaN       晴   北风3级           优
12 2025-04-02       28.0      18.0     NaN  东南风2级           良
13 2025-04-03        NaN      17.0       阴  西南风3级        轻度污染
14 2025-04-04        NaN       NaN      多云  东北风2级         NaN
15 2025-04-05       25.0      14.0      小雨   东风3级           良
16 2025-04-06       23.0       NaN       晴   南风2级           优
17 2025-04-07       22.0      11.0     NaN   西风2级         NaN
18 2025-04-08        NaN       NaN      多云   北风3级           良
19 2025-04-09        NaN       8.0       阴  东南风3级        轻度污染
20 2025-04-10       19.0       7.0      小雨  西南风2级         NaN
21 2025-04-11       21.0       NaN       晴  东北风3级           优
22 2025-04-12       24.0      13.0     NaN   东风2级           良
23 2025-04-13        NaN       NaN       晴   南风3级           良
24 2025-04-14        NaN      14.0       阴   西风2级         NaN
25 2025-04-15       28.0      16.0       晴   北风2级           优
26 2025-04-16        NaN       NaN      多云  东南风3级           良
27 2025-04-17       25.0      13.0      小雨  西南风3级         NaN
28 2025-04-18       23.0       NaN       晴  东北风2级           优
29 2025-04-19       21.0       9.0      多云   东风2级           良

In [209]:
#将日期设置为索引
# df.set_index(df['date'],drop=True,inplace=True)
df.set_index('date',inplace=True)
df
print(df.loc['2025-03-01':'2025-03-28'])

            high_temp  low_temp weather   wind air_quality
date
2025-03-21       18.0       7.0       晴  东北风2级           良
2025-03-22        NaN       NaN      多云   东风3级           良
2025-03-23        NaN      11.0      小雨   南风3级         NaN
2025-03-24       16.0       NaN       阴   西风2级           良
2025-03-25       19.0      10.0     NaN   北风2级           优
2025-03-26        NaN       NaN      多云  东南风3级           良
2025-03-27       24.0      14.0       晴  西南风2级         NaN
2025-03-28        NaN      13.0     NaN  东北风3级           良

In [220]:
# 时间间隔
# d1=pd.Timestamp('2013-01-15')
# d2=pd.Timestamp('2023-02-23')
# d3=d2-d1
# print(d3)
# print(type(d3))

df=pd.read_csv('data/xian_weather.csv',parse_dates=['date'])
# df.info()
# df['timedate']=pd.to_datetime(df['date'])
# df['timedate'].dt.day_name()
df['delta']=df['date']-df['date'][0]
df.set_index('delta',inplace=True)
print(df.loc['5 days':'25 days'])
df

              date  high_temp  low_temp weather   wind air_quality
delta
5 days  2025-03-26        NaN       NaN      多云  东南风3级           良
6 days  2025-03-27       24.0      14.0       晴  西南风2级         NaN
7 days  2025-03-28        NaN      13.0     NaN  东北风3级           良
8 days  2025-03-29       25.0      15.0       晴   东风2级           良
9 days  2025-03-30        NaN       NaN      小雨   南风2级        轻度污染
10 days 2025-03-31       21.0      11.0      多云   西风3级         NaN
11 days 2025-04-01       26.0       NaN       晴   北风3级           优
12 days 2025-04-02       28.0      18.0     NaN  东南风2级           良
13 days 2025-04-03        NaN      17.0       阴  西南风3级        轻度污染
14 days 2025-04-04        NaN       NaN      多云  东北风2级         NaN
15 days 2025-04-05       25.0      14.0      小雨   东风3级           良
16 days 2025-04-06       23.0       NaN       晴   南风2级           优
17 days 2025-04-07       22.0      11.0     NaN   西风2级         NaN
18 days 2025-04-08        NaN       NaN      多云   北风3级           良
19 days 2025-04-09        NaN       8.0       阴  东南风3级        轻度污染
20 days 2025-04-10       19.0       7.0      小雨  西南风2级         NaN
21 days 2025-04-11       21.0       NaN       晴  东北风3级           优
22 days 2025-04-12       24.0      13.0     NaN   东风2级           良
23 days 2025-04-13        NaN       NaN       晴   南风3级           良
24 days 2025-04-14        NaN      14.0       阴   西风2级         NaN
25 days 2025-04-15       28.0      16.0       晴   北风2级           优

              date  high_temp  low_temp weather   wind air_quality
delta
0 days  2025-03-21       18.0       7.0       晴  东北风2级           良
1 days  2025-03-22        NaN       NaN      多云   东风3级           良
2 days  2025-03-23        NaN      11.0      小雨   南风3级         NaN
3 days  2025-03-24       16.0       NaN       阴   西风2级           良
4 days  2025-03-25       19.0      10.0     NaN   北风2级           优
5 days  2025-03-26        NaN       NaN      多云  东南风3级           良
6 days  2025-03-27       24.0      14.0       晴  西南风2级         NaN
7 days  2025-03-28        NaN      13.0     NaN  东北风3级           良
8 days  2025-03-29       25.0      15.0       晴   东风2级           良
9 days  2025-03-30        NaN       NaN      小雨   南风2级        轻度污染
10 days 2025-03-31       21.0      11.0      多云   西风3级         NaN
11 days 2025-04-01       26.0       NaN       晴   北风3级           优
12 days 2025-04-02       28.0      18.0     NaN  东南风2级           良
13 days 2025-04-03        NaN      17.0       阴  西南风3级        轻度污染
14 days 2025-04-04        NaN       NaN      多云  东北风2级         NaN
15 days 2025-04-05       25.0      14.0      小雨   东风3级           良
16 days 2025-04-06       23.0       NaN       晴   南风2级           优
17 days 2025-04-07       22.0      11.0     NaN   西风2级         NaN
18 days 2025-04-08        NaN       NaN      多云   北风3级           良
19 days 2025-04-09        NaN       8.0       阴  东南风3级        轻度污染
20 days 2025-04-10       19.0       7.0      小雨  西南风2级         NaN
21 days 2025-04-11       21.0       NaN       晴  东北风3级           优
22 days 2025-04-12       24.0      13.0     NaN   东风2级           良
23 days 2025-04-13        NaN       NaN       晴   南风3级           良
24 days 2025-04-14        NaN      14.0       阴   西风2级         NaN
25 days 2025-04-15       28.0      16.0       晴   北风2级           优
26 days 2025-04-16        NaN       NaN      多云  东南风3级           良
27 days 2025-04-17       25.0      13.0      小雨  西南风3级         NaN
28 days 2025-04-18       23.0       NaN       晴  东北风2级           优
29 days 2025-04-19       21.0       9.0      多云   东风2级           良

In [ ]:
days=pd.date_range('2025-07-03','2026-02-09',freq='D')  #以day为周期
days=pd.date_range('2025-07-03',periods=10,freq='Y')  #periods=10意思是分为10个周期
days

DatetimeIndex(['2025-12-31', '2026-12-31', '2027-12-31', '2028-12-31',
               '2029-12-31', '2030-12-31', '2031-12-31', '2032-12-31',
               '2033-12-31', '2034-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [270]:
#重新采样
df=pd.read_csv('data/xian_weather.csv',parse_dates=['date'])
df.set_index('date',inplace=True)
df
df[['high_temp','low_temp']].resample('W').mean()

            high_temp  low_temp
date
2025-03-23      18.00      9.00
2025-03-30      21.00     13.00
2025-04-06      24.60     15.00
2025-04-13      21.50      9.75
2025-04-20      24.25     13.00

In [281]:
#数据采样中分组聚合
# df.groupby('分组字段')['聚合字段'].聚合函数()

df=pd.read_csv('data/employee.csv')
# df.info()
df.dropna(subset='salary')
df['salary']=df['salary'].astype('Int64')
# print(df['salary'].isna().sum())
#计算不同部门的平均工资保留两位小数
df.groupby('department')['salary'].mean().round(2).sort_values(ascending=False)
# df.groupby('department').groups  #查看分组
# df.groupby('department').get_group('技术部')  #查看具体的每个分组
# df2.sort_values('salary')

department
管理层     27000.0
技术部    11865.38
市场部    11366.67
财务部     11075.0
人事部     9809.09
Name: salary, dtype: Float64

In [ ]:
#计算不同部门不同工作年限的人的平均工资
df2=df.groupby(['department','work_years'])['salary'].mean()
df2=df2.reset_index()
df2.sort_values('salary',ascending=False)  #按照薪水求平均数,然后再降序排列

   department  work_years   salary
22        管理层          11  28000.0
21        管理层          10  26000.0
20        技术部           8  19600.0
12        市场部           7  18100.0
19        技术部           7  17600.0
29        财务部           7  17250.0
11        市场部           6  16100.0
18        技术部           6  15600.0
28        财务部           6  15450.0
5         人事部           6  14200.0
10        市场部           5  14150.0
17        技术部           5  13700.0
27        财务部           5  13600.0
4         人事部           5  12550.0
9         市场部           4  12150.0
26        财务部           4  11800.0
16        技术部           4  11700.0
3         人事部           4  10950.0
8         市场部           3  10150.0
25        财务部           3  10000.0
15        技术部           3   9925.0
2         人事部           3   9350.0
14        技术部           2   8425.0
24        财务部           2   8200.0
7         市场部           2   8150.0
1         人事部           2   7750.0
13        技术部           1   6975.0
23        财务部           1   6500.0
6         市场部           1   6500.0
0         人事部           1   6250.0

In [ ]:
#企鹅数据分析
# 1：导入必要的库
import pandas as  pd
import numpy  as np
# 2：导入数据
df=pd.read_csv('data/penguins.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1134 entries, 0 to 1133
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            1134 non-null   object
 1   island             1134 non-null   object
 2   bill_length_mm     1132 non-null   float64
 3   bill_depth_mm      1132 non-null   float64
 4   flipper_length_mm  1134 non-null   int64
 5   body_mass_g        1132 non-null   float64
 6   sex                1131 non-null   object
 7   year               1133 non-null   float64
dtypes: float64(4), int64(1), object(3)
memory usage: 71.0+ KB

In [ ]:
# 3：数据清洗
# 缺失值检查
print(df.isna().sum())
#删除缺失值,inplace=True立即生效
df.dropna(inplace=True) 
df.isna().sum()
len(df)

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

1128

In [314]:
# 4：数据特征构造
# df.head()
# 将性别转化为类别类型
df['sex']=df['sex'].astype('category')
df['bill_ratio']=df['bill_length_mm']/df['bill_depth_mm']
# df.info()
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,bill_ratio,体重等级,mess_level
0,Adelie,Torgersen,39.1,18.7,181,3750.0,MALE,2007.0,2.090909,低,低
1,Adelie,Torgersen,39.5,17.4,186,3800.0,FEMALE,2007.0,2.270115,低,低
2,Adelie,Torgersen,40.3,18.0,195,3250.0,FEMALE,2007.0,2.238889,低,低
4,Adelie,Torgersen,36.7,19.3,193,3450.0,FEMALE,2007.0,1.901554,低,低
5,Adelie,Torgersen,39.3,20.6,190,3650.0,MALE,2007.0,1.907767,低,低

In [342]:
# 5：数据分析
# 数据分箱,把体重分为低中高三个等级
labels=['低','中','高']
df['mess_level']=pd.cut(df['body_mass_g'],bins=3,labels=labels)
# df = df.drop('体重等级', axis=1) #删除某列
print(df['mess_level'].value_counts())
#按照岛屿和性别进行分组
df2=df.groupby(['island','sex']).agg({
    'body_mass_g':['mean','count']
}

)
df2=df2.reset_index()
df2

mess_level
中    494
高    411
低    223
Name: count, dtype: int64

      island     sex  body_mass_g
                             mean count
0     Biscoe  FEMALE  4466.860465   430
1     Biscoe    MALE  5376.298157   597
2      Dream  FEMALE  3579.310345    29
3      Dream    MALE  3917.741935    31
4  Torgersen  FEMALE  3505.263158    19
5  Torgersen    MALE  4005.681818    22

In [360]:
#睡眠数据分析
# 1：导入库
import pandas as pd
import numpy as np
# 2:导入数据
df=pd.read_json('data/sleep_data.json')
df.head()
# df.info()
# df.describe()
df.dropna(inplace=True)
df.isna().sum()

record_id         0
date              0
user_id           0
sleep_duration    0
deep_sleep        0
light_sleep       0
wake_times        0
sleep_score       0
heart_rate_avg    0
sleep_quality     0
dtype: int64

In [366]:
# 3:数据清洗
# df.isna().sum()
df['sleep_duration'].value_counts()
# df['deep_sleep'].value_counts()
# df['light_sleep'].value_counts()
# df['wake_times'].value_counts()
# df['sleep_score'].value_counts()
# df['heart_rate_avg'].value_counts()
# df['sleep_quality'].value_counts()
df['sleep_duration']=df['sleep_duration'].astype('category')
df.info()
#数据分箱
labels=['差','中','优']
df['sleep_quality']=pd.cut(df['deep_sleep'],bins=3,labels=labels)
sleep_labels=['没睡好','睡的还行','睡的很好']
df['睡眠质量']=pd.cut(df['sleep_score'],bins=3,labels=sleep_labels)
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 26 entries, 0 to 250
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   record_id       26 non-null     int64
 1   date            26 non-null     datetime64[ns]
 2   user_id         26 non-null     int64
 3   sleep_duration  26 non-null     category
 4   deep_sleep      26 non-null     float64
 5   light_sleep     26 non-null     float64
 6   wake_times      26 non-null     float64
 7   sleep_score     26 non-null     float64
 8   heart_rate_avg  26 non-null     float64
 9   sleep_quality   26 non-null     category
 10  睡眠质量            26 non-null     category
dtypes: category(3), datetime64[ns](1), float64(5), int64(2)
memory usage: 2.8 KB

,record_id,date,user_id,sleep_duration,deep_sleep,light_sleep,wake_times,sleep_score,heart_rate_avg,sleep_quality,睡眠质量
0,1,2025-01-01,101,7.2,1.8,5.4,2.0,78.0,68.0,中,没睡好
3,4,2025-01-04,101,8.1,2.2,5.9,1.0,88.0,66.0,优,睡的很好
20,21,2025-01-21,101,8.0,2.3,5.7,1.0,89.0,65.0,优,睡的很好
30,31,2025-02-01,101,7.7,2.1,5.6,1.0,84.0,66.0,优,睡的还行
40,41,2025-02-11,101,8.1,2.4,5.7,0.0,90.0,64.0,优,睡的很好

NameError: name 'quick_db_check' is not defined